# Generated by Django 4.2.7 on 2024-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_prod_art_products_prod_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_disc',
            field=models.CharField(max_length=50),
        ),
    ]
