# Generated by Django 4.2.7 on 2024-03-05 19:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_products_prod_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='prod_title', unique=True),
        ),
    ]
