# Generated by Django 4.2.7 on 2024-02-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_prod_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prod_art',
            new_name='prod_color',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prod_comp',
            new_name='prod_size',
        ),
    ]
