# Generated by Django 4.2.7 on 2024-02-22 12:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_products_prod_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_disc',
            field=tinymce.models.HTMLField(),
        ),
    ]
