# Generated by Django 4.2.7 on 2024-03-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='add1',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
