# Generated by Django 4.2.7 on 2024-03-09 07:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_registration_add1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='add1',
            field=tinymce.models.HTMLField(),
        ),
    ]
