# Generated by Django 4.2.7 on 2024-03-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0005_alter_registration_add1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='name1',
        ),
    ]
